name: Template Sync

on:
  # Cronjob trigger (runs on the 1st of every month at midnight)
  schedule:
  - cron: "0 0 1 * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    # Grant necessary permissions to create pull requests
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Checkout the dev branch with full history
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TEMPLATE_SYNC_PAT }}
          ref: dev
          fetch-depth: 0

      # Force Git to attach to the dev branch locally
      - name: Attach detached HEAD to dev branch
        run: git checkout -B dev

      # Run the template sync action and assign an ID to capture its outputs
      - name: actions-template-sync
        id: sync
        uses: AndreasAugustin/actions-template-sync@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TEMPLATE_SYNC_PAT }}
        with:
          source_repo_path: swiss-ai-center/create-a-new-service-generic-template
          upstream_branch: main
          pr_labels: template-sync,automated-pr
          source_gh_token: ${{ secrets.TEMPLATE_SYNC_PAT }}

      # Automatically change the PR target branch to dev using the GitHub CLI
      - name: Change PR base branch to dev
        if: steps.sync.outputs.pr_branch != ''
        env:
          # The GitHub CLI requires the GH_TOKEN environment variable
          GH_TOKEN: ${{ secrets.TEMPLATE_SYNC_PAT }}
        run: |
          gh pr edit ${{ steps.sync.outputs.pr_branch }} --base dev